# Google OIDC (production)
quarkus.oidc.provider=google
quarkus.oidc.client-id=${RECPS_APP_GOOGLE_CLIENT_ID}
quarkus.oidc.credentials.secret=${RECPS_APP_GOOGLE_CLIENT_SECRET}
quarkus.oidc.application-type=web-app

# Required: tells Quarkus to fetch UserInfo to validate the token
quarkus.oidc.authentication.user-info-required=true

%test.quarkus.oidc.auth-server-url=${keycloak.url}/realms/quarkus
%test.quarkus.oidc.client-id=quarkus-service-app
%test.quarkus.oidc.application-type=service
%test.quarkus.oidc.token.audience=https://id.server.example.com