# Database
quarkus.datasource.db-kind = postgresql

quarkus.datasource.username = user
%prod.quarkus.datasource.username = ${RECPS_APP_DB_USER}
quarkus.datasource.password = pass
%prod.quarkus.datasource.password = ${RECPS_APP_DB_PASSWORD}

%prod.quarkus.datasource.reactive.url=${RECPS_APP_DB_URL_REACTIVE}
%prod.quarkus.datasource.reactive.max-size=15
quarkus.datasource.reactive.trust-all=true
%prod.quarkus.datasource.jdbc.url=${RECPS_APP_DB_URL_JDBC}

quarkus.flyway.migrate-at-start = true
%test.quarkus.flyway.migrate-at-start = false

%dev.quarkus.flyway.locations=db/migration,db/testdata
%test.quarkus.flyway.locations=db/migration,db/testdata


quarkus.hibernate-orm.database.generation = none
%test.quarkus.hibernate-orm.database.generation = drop-and-create

%dev.quarkus.hibernate-orm.dev-ui.allow-hql = true

# OIDC
quarkus.oidc.provider=google
quarkus.oidc.client-id=${RECPS_APP_GOOGLE_CLIENT_ID}
quarkus.oidc.credentials.secret=${RECPS_APP_GOOGLE_CLIENT_SECRET}
quarkus.oidc.application-type=service

# Required: tells Quarkus to fetch UserInfo to validate the token
quarkus.oidc.authentication.user-info-required=true

%test.quarkus.oidc.auth-server-url=${keycloak.url}/realms/quarkus
%test.quarkus.oidc.client-id=quarkus-service-app
%test.quarkus.oidc.application-type=service
%test.quarkus.oidc.token.audience=https://id.server.example.com

# HTTP settings
quarkus.http.cors.enabled = true
%dev.quarkus.http.cors.origins = /.*/
%prod.quarkus.http.cors.origins = https://recps.app,http://recps.app
quarkus.http.cors.exposed-headers = Location
quarkus.http.port=${PORT:8080}

# Logging
quarkus.log.handler.file.application.enable = true
quarkus.log.handler.file.application.path = application.log
%test.quarkus.log.handler.file.application.path = application-test.log
quarkus.log.handler.file.application.format = %d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] %s%e%n

quarkus.log.category."app.recps".handlers = application
quarkus.log.category."app.recps".use-parent-handlers = false

%dev.quarkus.log.category."app.recps".level = DEBUG

%dev.quarkus.hibernate-orm.log.sql = true

%dev.quarkus.datasource.dev-ui.allow-sql=true
