create table recipe_collection
(
    id         bigint generated by default as identity,
    user_id    bigint not null,
    name       varchar(255),
    updated_at timestamptz,
    primary key (id)
);

create table collections_recipes
(
    collection_id bigint not null,
    recipe_id     bigint not null
);

alter table if exists recipe_collection
    add constraint fk_recipe_collection_user_id
    foreign key (user_id)
    references app_user;

alter table if exists collections_recipes
    add constraint fk_collections_recipes_collection_id
    foreign key (collection_id)
    references recipe_collection;

alter table if exists collections_recipes
    add constraint fk_collections_recipes_recipe_id
    foreign key (recipe_id)
    references recipe;
