create table categories_ingredients
(
    category_id   bigint not null,
    ingredient_id bigint not null
);

create table ingredient_category
(
    id      bigint generated by default as identity,
    user_id bigint,
    primary key (id)
);

create table ingredient_category_name
(
    id          bigint generated by default as identity,
    category_id bigint not null,
    language_id bigint not null,
    name        varchar(255),
    primary key (id)
);

create table app_user
(
    id    bigint generated by default as identity,
    email varchar(255),
    primary key (id)
);

alter table if exists app_user
    add constraint uq_email
    unique (email);

alter table if exists ingredient_category
    add constraint fk_ingredient_category_user_id
    foreign key (user_id)
    references app_user;

alter table if exists categories_ingredients
    add constraint fk_categories_ingredients_ingredient_id
    foreign key (ingredient_id)
    references ingredient;

alter table if exists categories_ingredients
    add constraint fk_categories_ingredients_ingredient_category_id
    foreign key (category_id)
    references ingredient_category;

alter table if exists ingredient_category_name
    add constraint fk_ingredient_category_name_ingredient_category_id
    foreign key (category_id)
    references ingredient_category;

alter table if exists ingredient_category_name
    add constraint fk_ingredient_category_name_language_id
    foreign key (language_id)
    references language;
