create table ingredient
(
    id bigint generated by default as identity,
    primary key (id)
);

create table ingredient_alternative_name
(
    id                 bigint generated by default as identity,
    name               varchar(255),
    ingredient_name_id bigint not null,
    primary key (id)
);

create table ingredient_name
(
    id              bigint generated by default as identity,
    name            varchar(255),
    relevance_score integer,
    ingredient_id   bigint,
    language_id     bigint,
    primary key (id)
);

create table language
(
    id       bigint generated by default as identity,
    iso_name varchar(255),
    primary key (id)
);

create table recipe
(
    id                 bigint generated by default as identity,
    cooking_time       smallint check ((cooking_time between 0 and 3)),
    image_url          oid,
    name               varchar(255),
    num_of_ingredients integer,
    url                oid,
    source_page_id     bigint,
    primary key (id)
);

create table recipe_ingredient
(
    id            bigint generated by default as identity,
    ingredient_id bigint not null,
    recipe_id     bigint not null,
    primary key (id)
);

create table source_page
(
    id          bigint generated by default as identity,
    name        varchar(255),
    language_id bigint not null,
    primary key (id)
);

alter table if exists ingredient_alternative_name
    add constraint fk_ingredient_alternative_name_ingredient_name_id
    foreign key (ingredient_name_id)
    references ingredient_name;

alter table if exists ingredient_name
    add constraint fk_ingredient_name_ingredient_id
    foreign key (ingredient_id)
    references ingredient;

alter table if exists ingredient_name
    add constraint fk_ingredient_name_language_id
    foreign key (language_id)
    references language;

alter table if exists recipe
    add constraint fk_recipe_source_page_id
    foreign key (source_page_id)
    references source_page;

alter table if exists recipe_ingredient
    add constraint fk_recipe_ingredient_ingredient_id
    foreign key (ingredient_id)
    references ingredient;

alter table if exists recipe_ingredient
    add constraint fk_recipe_ingredient_recipe_id
    foreign key (recipe_id)
    references recipe;

alter table if exists source_page
    add constraint fk_source_page_language_id
    foreign key (language_id)
    references language;

create index ix_ingredient_alternative_name_ingredient_name_id on ingredient_alternative_name (ingredient_name_id);

create index ix_ingredient_name_ingredient_id on ingredient_name (ingredient_id);

create index ix_ingredient_name_language_id on ingredient_name (language_id);

create index ix_recipe_source_page_id on recipe (source_page_id);

create index ix_recipe_ingredient_ingredient_id on recipe_ingredient (ingredient_id);

create index ix_recipe_ingredient_recipe_id on recipe_ingredient (recipe_id);

create index ix_source_page_language_id on source_page (language_id);