create table menu
(
    id bigint generated by default as identity,
    menu_plan_id bigint not null,
    primary key (id)
);

create table menus_recipes
(
    menu_id bigint not null,
    recipe_id bigint not null
);

create table menu_plan
(
    id          bigint generated by default as identity,
    user_id     bigint not null,
    name        varchar(255),
    primary key (id)
);

alter table if exists menu
    add constraint fk_menu_menu_plan_id
    foreign key (menu_plan_id)
    references menu_plan;

alter table if exists menus_recipes
    add constraint fk_menus_recipes_menu_id
    foreign key (menu_id)
    references menu;

alter table if exists menus_recipes
    add constraint fk_menus_recipes_recipe_id
    foreign key (recipe_id)
    references recipe;

alter table if exists menu_plan
    add constraint fk_menu_plan_user_id
    foreign key (user_id)
    references app_user;